# Generated by Django 3.1.7 on 2021-03-19 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiuser', '0003_auto_20210319_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='active',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='active',
        ),
    ]
