# Generated by Django 3.1.7 on 2021-03-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiuser', '0005_addstudent_addteacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teacherId',
        ),
        migrations.AlterField(
            model_name='addteacher',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
