# Generated by Django 3.1.7 on 2021-03-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiuser', '0006_auto_20210320_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addteacher',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
