# Generated by Django 3.1.7 on 2021-03-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiuser', '0007_auto_20210320_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='father',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
